---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    config.example.com/managed-by: gitops
    config.example.com/scm-url: git@github.com:cnuland/hello-chris-gitops.git
  labels:
    config.example.com/component: namespaces
  name: example-app
spec: