apiVersion: build.openshift.io/v1 
kind: BuildConfig 
metadata: 
    name: hello-chris-pipeline 
    namespace: test
spec: 
    nodeSelector: null 
    output: {} 
    postCommit: {} 
    resources: {} 
    runPolicy: Serial 
    source: 
        git: 
            uri: 'https://github.com/cnuland/hello-chris-gitops' 
        type: Git 
    strategy: 
        jenkinsPipelineStrategy: 
            jenkinsfilePath: Jenkinsfile 
        type: JenkinsPipeline