---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv3
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  - ReadOnlyMany
  nfs: 
    path: /nfs/non-prod/pv3
    server: 172.100.100.100
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
 